### ISSUE TITLE
Problem on Camera-Mesh Projection

### ISSUE THREAD

**Issue by curiosity654** [smartscenes/multiscan#18]
Hi, really thank you for the amazing work. I am currently working on the dataset and want to project camera stream to the point cloud but met with some problems and request for your help.
Here I briefly describe what I've done:

1. Extract vertex from the ply file to generate per scene point cloud (denoted as coords).
2. Use the coordinate transform in align json to transform pcd back to the unaligned point cloud.

```python
coordinate_transform = np.array([
        [-0.8240989189694418,   -1.2577625884568762e-16, -0.5664459124694938,       0.0],
        [-0.5664459124694938,   1.8298671888171506e-16,  0.8240989189694417,        0.0], 
        [0.0,                   1.0,                     -2.220446049250313e-16,    0.0],
        [-2.111092538711443,    -0.001395463943481453,  1.965826688114646,          1.0]
]).T
    
path_3d = data_dir_3d / (scene_name + ".pth")
data_3d = torch.load(path_3d)

coords, colors, obj_label, part_label = data_3d
coords = coords @ coordinate_transform[:3, :3] + coordinate_transform[:3, 3]
```

4. Read transform from corrosponding jsonl file, transform to Open3D camera coordinate and calculate inverse as in the doc

```python
def process_camera_pose(cam_params):
    # 解析 JSON 数据
    # cam_params = json.loads(jsonl_line)
    
    # 获取变换矩阵并重塑为4x4
    transform = np.asarray(cam_params.get('transform'))
    transform = np.reshape(transform, (4, 4), order='F')
    
    # 转换到 Open3D 相机坐标系
    coordinate_transform = np.diag([1, -1, -1, 1])
    transform = np.dot(transform, coordinate_transform)
    transform = transform / transform[3][3]
    
    # 获取相机外参（需要求逆）
    camera_extrinsics = np.linalg.inv(transform)
    
    # 从外参矩阵中提取位置和旋转
    rotation = camera_extrinsics[:3, :3]
    position = camera_extrinsics[:3, 3]
    
    return position, rotation
```

5. Log the camera extrinsic in visualization tool. (Here I use [Rerun](https://rerun.io/), from the doc, if extrinsic is provided, the param "from_parent" use be set as False to mark a direct transfrom from world coordinate)

```python
translation, rotation = process_camera_pose(pose_info[i * 10])

quat = R.from_matrix(rotation).as_quat()

# 记录带四元数的相机位姿
rr.log("world/camera", rr.Transform3D(
    translation=translation,
    rotation=rr.Quaternion(xyzw=quat),
    # from_parent=True
))

```
But After the above this is what I get, especially the translation seems very wierd. Here I use the first frame of scene_00000_00
![image](https://github.com/user-attachments/assets/d1b787fc-87a6-4206-b7a5-df2bdf1cb9b9)

Any advice is appreciated!

**Comment by curiosity654** [comment]
Update: I have solve the problem now, for anyone trying to do the same thing, I list the errors I made:
- The apply_transform of trimesh seems a little bit different from my operation above, so it's recommended to use trimesh to transform first and then extract points.
- I forgot to change the cx and cy in intrinsic after changing the image resolution.

**Comment by zfc00522** [comment]
hello,could you share the code about rerun and extrating the camera pose ? recently I'm also working on this, thanks a lot!

**Comment by curiosity654** [comment]
> hello,could you share the code about rerun and extrating the camera pose ? recently I'm also working on this, thanks a lot!

Sorry I'm busy working on another project. Maybe a few days later I will have time to organize the code. Before that, I suggest you go through the docs of multiscan carefully.

**Comment by zfc00522** [comment]
fine,thanks for your reply

**Comment by curiosity654** [comment]
> fine,thanks for your reply

Hi, this is the simple snippet, in case you still find it helpful.

https://gist.github.com/curiosity654/71204fbb5d10ba5e2dc95ab1defdc4e9

**Comment by zfc00522** [comment]
thanks！
