### ISSUE TITLE
Issue with build server

### ISSUE THREAD

**Issue by jeong-heo** [smartscenes/multiscan#3]
Thanks for your great work.

I have followed the processing server installation guide.
During the cmake, i got a fatal error and cmake terminated.
How can i fix this?

Thank you again.

 `[  3%] Building C object CMakeFiles/3rdparty_glew.dir/3rdparty/glew/src/glew.c.o
/home/jeongheo/Workspace/multiscan/build/open3d/3rdparty/glew/src/glew.c:41:12: fatal error: GL/osmesa.h: No such file or directory
   41 | #  include <GL/osmesa.h>
      |            ^~~~~~~~~~~~~
compilation terminated.
make[5]: *** [CMakeFiles/3rdparty_glew.dir/build.make:76: CMakeFiles/3rdparty_glew.dir/3rdparty/glew/src/glew.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:658: CMakeFiles/3rdparty_glew.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/open3d.dir/build.make:86: external/src/open3d-stamp/open3d-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/open3d.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

**Comment by jeong-heo** [comment]
I solved the issue myself.
The error disappeared with install libosmesa6-dev.
`sudo apt-get install libosmesa6-dev`
I'll close the issue. Thanks.

**Comment by doudoupx** [comment]
Hello！You have successfully set up the environment, can you communicate with me the details, I always fail in the process？Thanks.
